repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Swayam Chidrawar
title: BS Computer Science Freshman @ Cal Poly, San Luis Obispo
email: schidraw@calpoly.edu
website: https://linktr.ee/swaychidrawar

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BorealPanda
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sway.1351
linkedin_username: swayamchidrawar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: 	far fa-file-alt
  url: https://file.io/1KIGH30DZHwy
- title: itsgoingto.be
  icon: 	fas fa-trophy
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile3.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! my name is Swayam(He/Him/His) and I'm a BS Computer Science freshman at Cal Poly SLO. I'm interested in Machine Learning, Data Science and Web Development. I am looking for an internship for summer 2023 where I can get real world experience while also honing my skills. I am eligible to work in the United States.
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;I am most skilled in: <mark>Python</mark> , <mark>Java</mark> and <mark>SQL</mark>
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Touch-free hand sanitizer
        link: github.com/BorealPanda
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I made and distributed touch free hand sanitizer dispensers during the COVID-19 pandemic
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to help villages in India where COVID-19 was spreading rapidly. These devices were mainly used by local shops to ensure that their customers could stay safe. 
      
      
      - layout: top-middle
        title: Weather Prediction using Python
        link: github.com/BorealPanda
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Weather prediction program made using machine learning in python
        description: | # this will include new lines to allow paragraphs
          Dataset used: Los Angeles Airport(LAX) weather data downloaded from NOAA
          Tools used: Python, Jupyter, Pandas, NumPy, SQL
      - layout: top-middle
        title: Cricket match predictor
        link: github.com/BorealPanda
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Used to predict the outcomes of IPL matches.
        description: | # this will include new lines to allow paragraphs
          Data scrapped from cricinfo and other sources
          Tools used: Python, Jupyter, Pandas, NumPy, SQL
          
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Cal Poly, San Luis Obispo
        caption: 2022-2026
        sub_title: BS Computer Science w/Cross Disciplinary Minor in Data Science

      - layout: top-middle
        title: Pioneer Convent School
        caption: 2020-2022
        sub_title: Grade 12 (CBSE)
        quote: >
          Physics, Chemistry, Math, English
          96.8%
          Valedictorian
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Woodridge High School
        caption: 2018-2020
        sub_title: Grade 10 (CBSE)
        quote: >
          Physics, Chemistry, Math, English
          96.4%
          Valedictorian
        description: | # this will include new lines to allow paragraphs
  - title: Courses # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: CS50x - Introduction to Computing
        link: https://certificates.cs50.io/06fb9c42-3c87-4aaa-9b98-c8fe528921b0.pdf?size=letter
        link_text: CREDENTIALðŸ”—
        quote: >
          Harvard University/edX
      - layout: left
        title: Complete Python Bootcamp From Zero to Hero in Python
        link: https://www.udemy.com/certificate/UC-WQRIP0QK/
        link_text: CREDENTIALðŸ”—
        quote: >
          Udemy
      - layout: left
        title: Machine Learning, Data Science and Deep Learning with Python
        link: https://www.udemy.com/certificate/UC-ca9eec56-24b3-470d-bdaf-2740d985cedf/
        link_text: CREDENTIALðŸ”—
        quote: >
          Udemy
      - layout: left
        title: The Complete SQL Bootcamp- Go from Zero to Hero
        link: https://www.udemy.com/certificate/UC-d8b6f76c-be8a-4139-b263-352aaa79815e/
        link_text: CREDENTIALðŸ”—
        quote: >
          Udemy
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Tennis
      - Gaming
      - Cricket
      - Anime
      - Manga
      - 
      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag